version: '3.9'

services:
  api:
    build:
      context: ./ProjectManagement.Api
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings_DefaultConnection=Host=db;Port=5432;Database=pm_db;Username=postgres;Password=postgres

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: pm_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: